### ISSUE TITLE
Unable to use sux for javabridge and bioformats libraries

### ISSUE THREAD

**Issue by jni** [nicois/sux#2]
``` python
(bioformats3)
nuneziglesiasj@jni-lscc-mbp-10 Sat Dec 27 19:13 
 ~ $ export PY2_VIRTUAL_ENV=/Users/nuneziglesiasj/anaconda/envs/bioformats
(bioformats3)
nuneziglesiasj@jni-lscc-mbp-10 Sat Dec 27 19:13 
 ~ $ python
Python 3.4.2 |Continuum Analytics, Inc.| (default, Oct 21 2014, 17:42:20) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sux
>>> jv = sux.to_use('javabridge')
>>> bf = sux.to_use('bioformats')
>>> jv.start_vm([], class_path=bf.JARS)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nuneziglesiasj/anaconda/envs/bioformats3/lib/python3.4/site-packages/sux/__init__.py", line 130, in __call__
    kwargs=kwargs)
  File "/Users/nuneziglesiasj/anaconda/envs/bioformats3/lib/python3.4/site-packages/sux/__init__.py", line 106, in _value_or_reference
    exception_name.decode('utf-8'))(exception_text)
sux.KeyError: b'PATH'
```

My guess is that sux-launched processes don't inherit their parent environment?

**Comment by nicois** [comment]
Thanks for the report. I have added support for the environent to be specified. Check out version 0.1.5 and let me know how it goes. The README.md should help, and you can also check out the tests: https://github.com/nicois/sux/blob/master/tests/test_env.py

**Comment by jni** [comment]
@nicois fantastic, thanks for the speedy fix! Incidentally, I found that your first (and more intuitive) idiom didn't work, but the second one did:

``` python
>>> import sux
>>> import os
>>> jv = sux.to_use('javabridge', env=os.environ)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nuneziglesiasj/anaconda/envs/bioformats3/lib/python3.4/site-packages/sux/__init__.py", line 174, in to_use
    engine = Python2Engine.new(venv=PYTHON2_VENV, cwd=cwd, env=env)
  File "/Users/nuneziglesiasj/anaconda/envs/bioformats3/lib/python3.4/site-packages/sux/__init__.py", line 48, in new
    cache_key = dumps(kw)
_pickle.PicklingError: Can't pickle <function _createenviron.<locals>.encode at 0x1005e8d90>: attribute lookup encode on os failed
>>> jv = sux.to_use('javabridge', env=os.environ.__dict__['_data'])
>>> bf = sux.to_use('bioformats', env=os.environ.__dict__['_data'])
>>> jv.start_vm([], class_path=bf.JARS)
>>> 
```

Any chance of resolving this?
